spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: ""
    username: ""
    password: ""
server:
  id: ""
application:
  ids:
    fetch:
      size: 100
grpc:
  client:
    GLOBAL:
      address: static://localhost:9090
      negotiation-type: PLAINTEXT