spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/order_service"
    username: "admin"
    password: "password"
server:
  id: "1"
grpc:
  client:
    GLOBAL:
      address: static://localhost:9090
      negotiation-type: PLAINTEXT