spring:
  application:
    name: "order-service"
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/order_service"
    username: "admin"
    password: "password"
server:
  id: "1"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
grpc:
  client:
    GLOBAL:
      address: static://localhost:9090
      negotiation-type: PLAINTEXT